apiVersion: v1
kind: ReplicationController
metadata:
  name: arcade
spec:
  replicas: 3
  selector:
    app: arcade
  template:
    metadata:
      name: arcade
      labels:
        app: arcade
    spec:
      containers:
        - name: arcade
          image: tstrain199/nginx-arcade
          ports:
            - containerPort: 80
